version: "2"
services:
  mongo:
    container_name: db_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api_node:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
